# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ZC9vLNazhKoo7JfMrKbwL5qLUb1fL1U
"""

import pandas as pd
import numpy as np

a = pd.array([1,2,3,4])


my_list = [1,2,3]
my_list


arr = np.array(my_list)
arr


my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
mat

# the third parameter say, the step to step from one number to next number
ranges = np.arange(0,11,2)
ranges


for x in range(0,11,2):
  print(x)



np.zeros(3)
np.zeros((5,5))

np.ones((7,7))

np.linspace(0,5,10)

np.random.rand(5)

np.random.rand(5,5)

for x in np.random.rand(5,5):
  
  for y in x:
    
    if y > 0.5:
      print(y, "Got it")

label  = ['a','b','c']
my_data = [10,20,30]

arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

pd.Series(data=my_data, index=label)

pd.Series(d)

pd.Series(data=[sum, print, len])

ser1 = pd.Series([1,2,3,4],['USA', 'ECUADOR', 'JAPAN', 'Sweeden'])
ser1

ser2 = pd.Series([1,2,5,9],['USA', 'ECUADOR','Peru','Germany'])
ser2

ser1['USA']

ser1+ser2